CREATE SCHEMA IF NOT EXISTS ESC;

USE ESC;

CREATE TABLE TBTipoUsuario (
	TUSCodigo SMALLINT    NOT NULL AUTO_INCREMENT,
    TUSNome   VARCHAR(30) NOT NULL,
    PRIMARY KEY (TUSCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBUsuario (
	USUCodigo   BIGINT      NOT NULL AUTO_INCREMENT,
    USUId       VARCHAR(30) NOT NULL,
    USUSenha    TEXT        NOT NULL,
    USUAtivo    SMALLINT    NOT NULL DEFAULT 1,
    USUTermo    SMALLINT    NOT NULL DEFAULT 0,
    TUSCodigo   SMALLINT    NOT NULL,
	PRIMARY KEY (USUCodigo),
    FOREIGN KEY (TUSCodigo) REFERENCES TBTipoUsuario(TUSCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBPessoa (
	PESCodigo 		   BIGINT       NOT NULL AUTO_INCREMENT,
    PESNome            VARCHAR(100) NOT NULL,
    PESDataNascimento  DATE         NOT NULL,
    PESCpf 			   VARCHAR(11)  NOT NULL,
    PESRg 		       VARCHAR(7)  NOT NULL,
    USUCodigo 		   BIGINT 	    NOT NULL,
    PRIMARY KEY (PESCodigo),
    FOREIGN KEY (USUCodigo) REFERENCES TBUsuario(USUCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBAdmin (
    ADMCodigo BIGINT NOT NULL AUTO_INCREMENT,
    PESCodigo BIGINT NOT NULL,
    PRIMARY KEY (ADMCodigo),
    FOREIGN KEY (PESCodigo) REFERENCES TBPessoa(PESCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBProfessor (
    PROCodigo BIGINT NOT NULL AUTO_INCREMENT,
    PESCodigo BIGINT NOT NULL,
    PRIMARY KEY (PROCodigo),
    FOREIGN KEY (PESCodigo) REFERENCES TBPessoa(PESCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBAluno (
    ALUCodigo BIGINT NOT NULL AUTO_INCREMENT,
    PESCodigo BIGINT NOT NULL,
    PRIMARY KEY (ALUCodigo),
    FOREIGN KEY (PESCodigo) REFERENCES TBPessoa(PESCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBResponsavel (
    RESCodigo BIGINT NOT NULL AUTO_INCREMENT,
    PESCodigo BIGINT NOT NULL,
    PRIMARY KEY (RESCodigo),
    FOREIGN KEY (PESCodigo) REFERENCES TBPessoa(PESCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBResponsavelAluno (
	RESCodigo   BIGINT   NOT NULL,
    ALUCodigo   BIGINT   NOT NULL, 
    AREFiliacao SMALLINT NOT NULL,
    PRIMARY KEY (RESCodigo, ALUCodigo),
    FOREIGN KEY (RESCodigo) REFERENCES TBResponsavel(RESCodigo),
    FOREIGN KEY (ALUCodigo) REFERENCES TBAluno(ALUCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBMateria (
	MATCodigo    INTEGER      NOT NULL AUTO_INCREMENT,
    MATNome      VARCHAR(50)  NOT NULL,
    MATDescricao VARCHAR(500) NOT NULL,
    PRIMARY KEY (MATCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBSalaVirtual (
	SALCodigo    INTEGER      NOT NULL AUTO_INCREMENT,
    SALDescricao VARCHAR(500) NOT NULL,
    MATCodigo    INTEGER      NOT NULL,
    PRIMARY KEY (SALCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBSalaVirtualProfessor (
	PROCodigo BIGINT  NOT NULL,
    SALCodigo INTEGER NOT NULL, 
    PRIMARY KEY (PROCodigo, SALCodigo),
    FOREIGN KEY (PROCodigo) REFERENCES TBProfessor(PROCodigo),
    FOREIGN KEY (SALCodigo) REFERENCES TBSalaVirtual(SALCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBSalaVirtualAluno (
	SALCodigo INTEGER NOT NULL,
    ALUCodigo BIGINT  NOT NULL,
    PRIMARY KEY (SALCodigo, ALUCodigo),
    FOREIGN KEY (SALCodigo) REFERENCES TBSalaVirtual(SALCodigo),
    FOREIGN KEY (ALUCodigo) REFERENCES TBAluno(ALUCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBRegistroAula (
	RAUCodigo    INTEGER      NOT NULL AUTO_INCREMENT, 
    RAUDescricao VARCHAR(500) NOT NULL,
    RAUData      DATE         NOT NULL,
    PROCodigo 	 BIGINT 	  NOT NULL,
    SALCodigo    INTEGER      NOT NULL,
    PRIMARY KEY (RAUCodigo),
    FOREIGN KEY (SALCodigo) REFERENCES TBSalaVirtual(SALCodigo),
    FOREIGN KEY (PROCodigo) REFERENCES TBSalaVirtualProfessor(PROCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE TBRegistroAulaAluno (
	RAUCodigo INTEGER NOT NULL,
    ALUCodigo BIGINT  NOT NULL,
    PRIMARY KEY (RAUCodigo, ALUCodigo),
    FOREIGN KEY (RAUCodigo) REFERENCES TBRegistroAula(RAUCodigo),
    FOREIGN KEY (ALUCodigo) REFERENCES TBSalaVirtualAluno(ALUCodigo)
)ENGINE=InnoDB DEFAULT CHARSET=latin1;