CREATE SCHEMA IF NOT EXISTS TST;
USE TST;

CREATE TABLE IF NOT EXISTS tbestrangeiro(
	codigo INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS tbaluno (
	id INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(45) NOT NULL,
    dataTeste DATE NOT NULL,
    codigo INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (codigo) REFERENCES tbestrangeiro(codigo)
);

SELECT * FROM TBAluno;